### ISSUE TITLE
Required torch version dosn't exist.

### ISSUE THREAD

**Issue by MeepChangeling** [Bertral/wrAIter#3]
Not much else to say but what it says on the tin. Which is a shame. I wanted to use this :/

**Comment by FontaineRiant** [comment]
This happens when you have python 3.10 which isn't supported by pytorch yet (except for nightly builds). You could install an older version of python (I'm using 3.9) and replace
`python -m venv venv`
with
`python3.9 -m venv venv` (or whatever vesion you picked)
inside `install.sh` (or `install.ps1` for powershell, it should work the same way)
